// <auto-generated />
using System;
using Codenation.Challenge.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Source.Migrations
{
    [DbContext(typeof(CodenationContext))]
    partial class CodenationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Codenation.Challenge.Models.Company", b =>
                {
                    b.Property<int>("Company_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created_At");

                    b.Property<string>("Name");

                    b.Property<string>("Slug");

                    b.HasKey("Company_Id");

                    b.ToTable("company");
                });

            modelBuilder.Entity("Source.Models.Acceleration", b =>
                {
                    b.Property<int>("Acceleration_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Challenge_Id");

                    b.Property<DateTime>("Created_At");

                    b.Property<string>("Name");

                    b.Property<string>("Slug");

                    b.HasKey("Acceleration_Id");

                    b.HasIndex("Challenge_Id");

                    b.ToTable("acceleration");
                });

            modelBuilder.Entity("Source.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Acceleration_Id");

                    b.Property<int>("Company_Id");

                    b.Property<DateTime>("Created_At");

                    b.Property<int>("Status");

                    b.Property<int>("User_Id");

                    b.HasKey("Id");

                    b.HasIndex("Acceleration_Id");

                    b.HasIndex("Company_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("candidate");
                });

            modelBuilder.Entity("Source.Models.Challenge", b =>
                {
                    b.Property<int>("Challenge_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created_At");

                    b.Property<string>("Name");

                    b.Property<string>("Slug");

                    b.HasKey("Challenge_Id");

                    b.ToTable("challenge");
                });

            modelBuilder.Entity("Source.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Challenge_Id");

                    b.Property<DateTime>("Created_At");

                    b.Property<decimal>("Score");

                    b.Property<int>("User_Id");

                    b.HasKey("Id");

                    b.HasIndex("Challenge_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("submission");
                });

            modelBuilder.Entity("Source.Models.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created_At");

                    b.Property<string>("Email");

                    b.Property<string>("Full_Name");

                    b.Property<string>("Nickname");

                    b.Property<string>("Password");

                    b.HasKey("User_Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("Source.Models.Acceleration", b =>
                {
                    b.HasOne("Source.Models.Challenge")
                        .WithMany("Accelerations")
                        .HasForeignKey("Challenge_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Source.Models.Candidate", b =>
                {
                    b.HasOne("Source.Models.Acceleration", "Acceleration")
                        .WithMany("Candidates")
                        .HasForeignKey("Acceleration_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Codenation.Challenge.Models.Company", "Company")
                        .WithMany("Candidates")
                        .HasForeignKey("Company_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Source.Models.User", "User")
                        .WithMany("Candidates")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Source.Models.Submission", b =>
                {
                    b.HasOne("Source.Models.Challenge", "Challenge")
                        .WithMany("Submissions")
                        .HasForeignKey("Challenge_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Source.Models.User", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
